apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: ridesharing
data:
  KAFKA_BROKERS: "kafka-broker-0.kafka-headless.ridesharing.svc.cluster.local:9092,kafka-broker-1.kafka-headless.ridesharing.svc.cluster.local:9092,kafka-broker-2.kafka-headless.ridesharing.svc.cluster.local:9092"
  KAFKA_TOPICS: "gps-critical,gps-surge,gps-normal"
  WINDOW_SECONDS: "10"
  AWS_DEFAULT_REGION: "ap-south-1"
  CHECKPOINT_DIR: "s3://ridesharing-pipeline-h20250060/checkpoints/k8s/"
  JAR_PATH: "/app/jars"
