apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: ridesharing
data:
  KAFKA_BROKERS: "kafka-broker-0.kafka-headless.ridesharing.svc.cluster.local:9092,kafka-broker-1.kafka-headless.ridesharing.svc.cluster.local:9092,kafka-broker-2.kafka-headless.ridesharing.svc.cluster.local:9092"
  KAFKA_TOPICS: "gps-critical,gps-surge,gps-normal"
  SCALE_LEVEL: "5K"
  WINDOW_SECONDS: "5"
  NUM_DRIVERS: "5000"
  AWS_DEFAULT_REGION: "ap-south-1"
  AWS_REGION: "ap-south-1"
  CHECKPOINT_DIR: "/tmp/spark-checkpoints"
  JAR_PATH: "/app/jars"
